swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/profile/{accountId}/transaction:
    get:
      tags:
      - Transactions
      security:
        - Bearer: []
      summary: Récupérer les transactions pour une carte bancaire spécifique
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: Identifiant du compte bancaire utilisateur
        type: string
        required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Ressource introuvable
        '401': 
          description: Non autorisé (authentification requise)
        '500':
          description: Erreur interne du serveur
          
  /user/transactions/{transactionId}:
    get:
      tags:
          - Transactions
      security:
        - Bearer: []
      summary: Récupérer les détails d'une transaction spécifique
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: transactionId
        type: string
        required: true
        description: Identifiant de la transaction
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/TransactionDetails"
        '404':
          description: Ressource introuvable
        '401': 
          description: Non autorisé (authentification requise)
        '500':
          description: Erreur interne du serveur
  /user/transactions/{transactionId}/category:
    patch:
      tags:
          - Transactions
      summary: Modifier la catégorie d'une transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: transactionId
        type: string
        required: true
        description: Identifiant de la transaction
      - in: body
        name: body
        schema:
          $ref: "#/definitions/TransactionCategoryUpdate"
        required: true
      responses:
        '200':
          description: Modification réussie
        '400':
          description: Requête invalide
        '401': 
          description: Non autorisé (authentification requise)
        '500':
          description: Erreur interne du serveur
    delete:
      tags:
        - Transactions
      summary: Supprimer la catégorie d'une transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: transactionId
        type: string
        required: true
        description: Identifiant de la transaction
      responses:
        '204':
          description: Suppression réussie
        '400':
          description: Requête invalide
        '401': 
          description: Non autorisé (authentification requise)
        '500':
          description: Erreur interne du serveur      
  /user/transactions/{transactionId}/notes:        
    patch:
      tags:
          - Transactions
      summary: Modifier la note d'une transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: transactionId
        type: string
        required: true
        description: Identifiant de la transaction
      - in: body
        name: body
        schema:
          $ref: "#/definitions/TransactionNotesUpdate"
        required: true
      responses:
        '200':
          description: Modification réussie
        '400':
          description: Requête invalide
        '401': 
          description: Non autorisé (authentification requise)
        '500':
          description: Erreur interne du serveur
        
    delete:
      tags:
        - Transactions
      summary: Supprimer la note d'une transaction
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: transactionId
        type: string
        required: true
        description: Identifiant de la transaction
      responses:
        '204':
          description: Suppression réussie
        '400':
          description: Requête invalide
        '401': 
          description: Non autorisé (authentification requise)
        '500':
          description: Erreur interne du serveur           
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: integer
        description: La somme de la transaction
      balance:
        type: integer
        description: Le solde apres la transaction
  TransactionDetails:
    type: object
    properties:
      id:
        type: string
        description: Identifiant unique de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      category:
        type: string
        description: Catégorie de la transaction
      notes:
        type: string
        description: Notes de la transaction
      amount:
        type: number
        format: float
        description: Montant de la transaction
  TransactionCategoryUpdate:
    type: object
    properties:
      category:
        type: string
        description: Nouvelle catégorie de la transaction
  TransactionNotesUpdate:
    type: object
    properties:
      notes:
        type: string
        description: Nouvelle note de la transaction